export const manifest = {
  id: 'org.sdoolman.alomoves',
  version: '1.1.1',
  name: 'Alo Wellness Club',
  description:
    'Stream Alo Moves and Alo Wellness Club fitness, yoga, and mindfulness programs directly in Stremio.',
  logo: 'https://d357mttm70bw7x.cloudfront.net/37ac722a-09b9-4ad2-8a7c-739e84c826c0.jpg',
  background: 'https://d357mttm70bw7x.cloudfront.net/37ac722a-09b9-4ad2-8a7c-739e84c826c0.jpg',
  resources: [
    'catalog',
    {
      name: 'meta',
      types: ['series'],
      idPrefixes: ['alo:'],
    },
    {
      name: 'stream',
      types: ['series'],
      idPrefixes: ['alo:'],
    },
  ],
  types: ['series'],
  idPrefixes: ['alo:'],
  catalogs: [
    {
      type: 'series',
      id: 'alo_yoga',
      name: 'ALO MOVES | Yoga',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'All Yoga',
            'Ashtanga',
            'Hatha',
            'Kundalini',
            'Prenatal',
            'Restorative',
            'Vinyasa',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_fitness',
      name: 'ALO MOVES | Fitness',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'All Fitness',
            'Barre',
            'Core',
            'Dance',
            'Gym',
            'HIIT',
            'Pilates',
            'Prenatal/Postnatal',
            'Running',
            'Sculpt',
            'Strength',
            'Stretching',
            'Walking',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_mindfulness',
      name: 'ALO MOVES | Mindfulness',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'All Mindfulness',
            'Breathwork',
            'Meditation',
            'Reiki',
            'Sound',
            'Yoga Nidra',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_wellness',
      name: 'ALO MOVES | Wellness',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'All Wellness',
            'Cycle Syncing',
            'Education',
            'Nutrition',
            'Personal Growth',
            'Recovery',
            'Sleep',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_skills',
      name: 'ALO MOVES | Skills',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'All Skills',
            'Arm Balances',
            'Backbends',
            'Flexibility',
            'How to Teach',
            'Inversions',
            'Mobility',
            'Yoga Poses',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_duration',
      name: 'ALO MOVES | Duration',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            '5-15 mins',
            '15-30 mins',
            '30-45 mins',
            '45-60 mins',
            '60+ mins',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_focus',
      name: 'ALO MOVES | Focus Area',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'Full Body',
            'Arms',
            'Core',
            'Booty',
            'Legs',
            'Chest',
            'Back',
            'Hips',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_equipment',
      name: 'ALO MOVES | Equipment',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'No Equipment',
            'Weights',
            'Resistance Band',
            'Blocks',
            'Strap',
            'Sliders',
            'Kettlebells',
            'Foam Roller',
            'Pilates Ring',
            'Ankle Weights',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_difficulty',
      name: 'ALO MOVES | Difficulty',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: ['Beginner', 'Moderate', 'Intermediate', 'Advanced'],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_intensity',
      name: 'ALO MOVES | Intensity',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: ['Level 1', 'Level 2', 'Level 3', 'Level 4'],
        },
        { name: 'skip', isRequired: false },
      ],
    },
    {
      type: 'series',
      id: 'alo_instructors',
      name: 'ALO MOVES | Instructors',
      posterShape: 'landscape',
      extra: [
        { name: 'search', isRequired: false },
        {
          name: 'genre',
          isRequired: false,
          options: [
            'Dylan Werner',
            'Ashley Galvin',
            'Briohny Smyth',
            'Caley Alyssa',
            'Tawny Janae',
            'Jacy Cunningham',
            'Daniel Scott',
            'Koya Webb',
            'Emily Sferra',
            'Patrick Beach',
            'Carling Harps',
            'Dice Iida-Klein',
            'Christa Janine',
            'Matt Giordano',
            'Kayla Nielsen',
            'Josh Kramer',
            'Naya Rappaport',
            'Roxanne Gan',
            'Meghan Currie',
            'Annie Moves',
          ],
        },
        { name: 'skip', isRequired: false },
      ],
    },
  ],
};
